- name: Container is running
  docker:
    image: elasticsearch
    name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
  tags: [elasticsearch]